camera:
  index: 1
  width: 1920
  height: 1080
  fps: 60

display:
  show_local_preview: true

model:
  path: model/face_landmarker.task

mask:
  enabled: true
  image_path: assets/masks/CA.png
  top_padding_ratio: 0.55
  bottom_padding_ratio: 0.10
  horizontal_padding_ratio: 0.90
  vertical_offset_ratio: 0.0
